import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/supported',
          '/how-it-works',
          '/faq',
          '/privacy-policy',
          '/terms-of-service',
          '/instagram-downloader',
          '/download-instagram-videos',
          '/instagram-reels-downloader',
          '/instagram-video-downloader',
          '/free-instagram-downloader',
          '/instagram-story-downloader',
          '/download-instagram-reels',
          '/instagram-to-mp4',
          '/save-instagram-videos',
          '/instagram-video-saver',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/temp/',
          '*.json',
          '*.xml',
          '/download/*',
          '/user/',
          '/dashboard/',
          '/settings/',
          '/profile/',
          '/login/',
          '/register/',
          '/reset-password/',
          '/verify-email/',
          '/404',
          '/500',
          '/error',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/supported',
          '/how-it-works',
          '/faq',
          '/privacy-policy',
          '/terms-of-service',
          '/instagram-downloader',
          '/download-instagram-videos',
          '/instagram-reels-downloader',
          '/instagram-video-downloader',
          '/free-instagram-downloader',
          '/instagram-story-downloader',
          '/download-instagram-reels',
          '/instagram-to-mp4',
          '/save-instagram-videos',
          '/instagram-video-saver',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/temp/',
          '/download/*',
          '/user/',
          '/dashboard/',
          '/settings/',
          '/profile/',
          '/login/',
          '/register/',
          '/reset-password/',
          '/verify-email/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/supported',
          '/how-it-works',
          '/faq',
          '/privacy-policy',
          '/terms-of-service',
          '/instagram-downloader',
          '/download-instagram-videos',
          '/instagram-reels-downloader',
          '/instagram-video-downloader',
          '/free-instagram-downloader',
          '/instagram-story-downloader',
          '/download-instagram-reels',
          '/instagram-to-mp4',
          '/save-instagram-videos',
          '/instagram-video-saver',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/temp/',
          '/download/*',
          '/user/',
          '/dashboard/',
          '/settings/',
          '/profile/',
          '/login/',
          '/register/',
          '/reset-password/',
          '/verify-email/',
        ],
        crawlDelay: 2,
      },
      {
        userAgent: 'Slurp',
        allow: [
          '/',
          '/supported',
          '/how-it-works',
          '/faq',
          '/privacy-policy',
          '/terms-of-service',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/temp/',
          '/download/*',
        ],
        crawlDelay: 3,
      },
      {
        userAgent: 'DuckDuckBot',
        allow: [
          '/',
          '/supported',
          '/how-it-works',
          '/faq',
          '/privacy-policy',
          '/terms-of-service',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/private/',
          '/temp/',
          '/download/*',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: 'https://fintok.com/sitemap.xml',
    host: 'https://fintok.com',
  }
}
